// City centers verified through Open-Meteo / GeoNames. Retrieved 2026-10-03.
export const MORE_LOCATIONS = [
    {
        "id":  "manila",
        "name":  "Manila",
        "latitude":  14.6042,
        "longitude":  120.9822,
        "timeZone":  "Asia/Manila",
        "group":  "Philippines",
        "geonameId":  1701668,
        "country":  "Philippines",
        "source":  "https://geocoding-api.open-meteo.com/v1/search?name=Manila\u0026count=10\u0026language=en\u0026format=json\u0026countryCode=PH"
    },
    {
        "id":  "quezon-city",
        "name":  "Quezon City",
        "latitude":  14.6488,
        "longitude":  121.0509,
        "timeZone":  "Asia/Manila",
        "group":  "Philippines",
        "geonameId":  1692192,
        "country":  "Philippines",
        "source":  "https://geocoding-api.open-meteo.com/v1/search?name=Quezon%20City\u0026count=10\u0026language=en\u0026format=json\u0026countryCode=PH"
    },
    {
        "id":  "cebu",
        "name":  "Cebu City",
        "latitude":  10.31672,
        "longitude":  123.89071,
        "timeZone":  "Asia/Manila",
        "group":  "Philippines",
        "geonameId":  1717512,
        "country":  "Philippines",
        "source":  "https://geocoding-api.open-meteo.com/v1/search?name=Cebu%20City\u0026count=10\u0026language=en\u0026format=json\u0026countryCode=PH"
    },
    {
        "id":  "davao",
        "name":  "Davao",
        "latitude":  7.07306,
        "longitude":  125.61278,
        "timeZone":  "Asia/Manila",
        "group":  "Philippines",
        "geonameId":  1715348,
        "country":  "Philippines",
        "source":  "https://geocoding-api.open-meteo.com/v1/search?name=Davao\u0026count=10\u0026language=en\u0026format=json\u0026countryCode=PH"
    },
    {
        "id":  "baguio",
        "name":  "Baguio",
        "latitude":  16.41639,
        "longitude":  120.59306,
        "timeZone":  "Asia/Manila",
        "group":  "Philippines",
        "geonameId":  1728930,
        "country":  "Philippines",
        "source":  "https://geocoding-api.open-meteo.com/v1/search?name=Baguio\u0026count=10\u0026language=en\u0026format=json\u0026countryCode=PH"
    },
    {
        "id":  "iloilo",
        "name":  "Iloilo",
        "latitude":  10.69694,
        "longitude":  122.56444,
        "timeZone":  "Asia/Manila",
        "group":  "Philippines",
        "geonameId":  1711005,
        "country":  "Philippines",
        "source":  "https://geocoding-api.open-meteo.com/v1/search?name=Iloilo\u0026count=10\u0026language=en\u0026format=json\u0026countryCode=PH"
    },
    {
        "id":  "bacolod",
        "name":  "Bacolod",
        "latitude":  10.66667,
        "longitude":  122.95,
        "timeZone":  "Asia/Manila",
        "group":  "Philippines",
        "geonameId":  1729564,
        "country":  "Philippines",
        "source":  "https://geocoding-api.open-meteo.com/v1/search?name=Bacolod\u0026count=10\u0026language=en\u0026format=json\u0026countryCode=PH"
    },
    {
        "id":  "cagayan-de-oro",
        "name":  "Cagayan de Oro",
        "latitude":  8.48222,
        "longitude":  124.64722,
        "timeZone":  "Asia/Manila",
        "group":  "Philippines",
        "geonameId":  1721080,
        "country":  "Philippines",
        "source":  "https://geocoding-api.open-meteo.com/v1/search?name=Cagayan%20de%20Oro\u0026count=10\u0026language=en\u0026format=json\u0026countryCode=PH"
    },
    {
        "id":  "puerto-princesa",
        "name":  "Puerto Princesa",
        "latitude":  9.73917,
        "longitude":  118.73528,
        "timeZone":  "Asia/Manila",
        "group":  "Philippines",
        "geonameId":  1692685,
        "country":  "Philippines",
        "source":  "https://geocoding-api.open-meteo.com/v1/search?name=Puerto%20Princesa\u0026count=10\u0026language=en\u0026format=json\u0026countryCode=PH"
    },
    {
        "id":  "zamboanga",
        "name":  "Zamboanga",
        "latitude":  6.91028,
        "longitude":  122.07389,
        "timeZone":  "Asia/Manila",
        "group":  "Philippines",
        "geonameId":  1679432,
        "country":  "Philippines",
        "source":  "https://geocoding-api.open-meteo.com/v1/search?name=Zamboanga\u0026count=10\u0026language=en\u0026format=json\u0026countryCode=PH"
    },
    {
        "id":  "bangkok",
        "name":  "Bangkok",
        "latitude":  13.75398,
        "longitude":  100.50144,
        "timeZone":  "Asia/Bangkok",
        "group":  "Asia \u0026 Pacific",
        "geonameId":  1609350,
        "country":  "Thailand",
        "source":  "https://geocoding-api.open-meteo.com/v1/search?name=Bangkok\u0026count=10\u0026language=en\u0026format=json\u0026countryCode=TH"
    },
    {
        "id":  "hong-kong",
        "name":  "Hong Kong",
        "latitude":  22.27832,
        "longitude":  114.17469,
        "timeZone":  "Asia/Hong_Kong",
        "group":  "Asia \u0026 Pacific",
        "geonameId":  1819729,
        "country":  null,
        "source":  "https://geocoding-api.open-meteo.com/v1/search?name=Hong%20Kong\u0026count=10\u0026language=en\u0026format=json\u0026countryCode=HK"
    },
    {
        "id":  "jakarta",
        "name":  "Jakarta",
        "latitude":  -6.21462,
        "longitude":  106.84513,
        "timeZone":  "Asia/Jakarta",
        "group":  "Asia \u0026 Pacific",
        "geonameId":  1642911,
        "country":  "Indonesia",
        "source":  "https://geocoding-api.open-meteo.com/v1/search?name=Jakarta\u0026count=10\u0026language=en\u0026format=json\u0026countryCode=ID"
    },
    {
        "id":  "kuala-lumpur",
        "name":  "Kuala Lumpur",
        "latitude":  3.1412,
        "longitude":  101.68653,
        "timeZone":  "Asia/Kuala_Lumpur",
        "group":  "Asia \u0026 Pacific",
        "geonameId":  1735161,
        "country":  "Malaysia",
        "source":  "https://geocoding-api.open-meteo.com/v1/search?name=Kuala%20Lumpur\u0026count=10\u0026language=en\u0026format=json\u0026countryCode=MY"
    },
    {
        "id":  "seoul",
        "name":  "Seoul",
        "latitude":  37.566,
        "longitude":  126.9784,
        "timeZone":  "Asia/Seoul",
        "group":  "Asia \u0026 Pacific",
        "geonameId":  1835848,
        "country":  "South Korea",
        "source":  "https://geocoding-api.open-meteo.com/v1/search?name=Seoul\u0026count=10\u0026language=en\u0026format=json\u0026countryCode=KR"
    },
    {
        "id":  "taipei",
        "name":  "Taipei",
        "latitude":  25.05306,
        "longitude":  121.52639,
        "timeZone":  "Asia/Taipei",
        "group":  "Asia \u0026 Pacific",
        "geonameId":  1668341,
        "country":  "Taiwan",
        "source":  "https://geocoding-api.open-meteo.com/v1/search?name=Taipei\u0026count=10\u0026language=en\u0026format=json\u0026countryCode=TW"
    },
    {
        "id":  "auckland",
        "name":  "Auckland",
        "latitude":  -36.84853,
        "longitude":  174.76349,
        "timeZone":  "Pacific/Auckland",
        "group":  "Asia \u0026 Pacific",
        "geonameId":  2193733,
        "country":  "New Zealand",
        "source":  "https://geocoding-api.open-meteo.com/v1/search?name=Auckland\u0026count=10\u0026language=en\u0026format=json\u0026countryCode=NZ"
    },
    {
        "id":  "dubai",
        "name":  "Dubai",
        "latitude":  25.07725,
        "longitude":  55.30927,
        "timeZone":  "Asia/Dubai",
        "group":  "Asia \u0026 Pacific",
        "geonameId":  292223,
        "country":  "United Arab Emirates",
        "source":  "https://geocoding-api.open-meteo.com/v1/search?name=Dubai\u0026count=10\u0026language=en\u0026format=json\u0026countryCode=AE"
    },
    {
        "id":  "paris",
        "name":  "Paris",
        "latitude":  48.85341,
        "longitude":  2.3488,
        "timeZone":  "Europe/Paris",
        "group":  "Europe",
        "geonameId":  2988507,
        "country":  "France",
        "source":  "https://geocoding-api.open-meteo.com/v1/search?name=Paris\u0026count=10\u0026language=en\u0026format=json\u0026countryCode=FR"
    },
    {
        "id":  "rome",
        "name":  "Rome",
        "latitude":  41.89193,
        "longitude":  12.51133,
        "timeZone":  "Europe/Rome",
        "group":  "Europe",
        "geonameId":  3169070,
        "country":  "Italy",
        "source":  "https://geocoding-api.open-meteo.com/v1/search?name=Rome\u0026count=10\u0026language=en\u0026format=json\u0026countryCode=IT"
    },
    {
        "id":  "berlin",
        "name":  "Berlin",
        "latitude":  52.52437,
        "longitude":  13.41053,
        "timeZone":  "Europe/Berlin",
        "group":  "Europe",
        "geonameId":  2950159,
        "country":  "Germany",
        "source":  "https://geocoding-api.open-meteo.com/v1/search?name=Berlin\u0026count=10\u0026language=en\u0026format=json\u0026countryCode=DE"
    },
    {
        "id":  "madrid",
        "name":  "Madrid",
        "latitude":  40.4165,
        "longitude":  -3.70256,
        "timeZone":  "Europe/Madrid",
        "group":  "Europe",
        "geonameId":  3117735,
        "country":  "Spain",
        "source":  "https://geocoding-api.open-meteo.com/v1/search?name=Madrid\u0026count=10\u0026language=en\u0026format=json\u0026countryCode=ES"
    },
    {
        "id":  "los-angeles",
        "name":  "Los Angeles",
        "latitude":  34.05223,
        "longitude":  -118.24368,
        "timeZone":  "America/Los_Angeles",
        "group":  "Americas",
        "geonameId":  5368361,
        "country":  "United States",
        "source":  "https://geocoding-api.open-meteo.com/v1/search?name=Los%20Angeles\u0026count=10\u0026language=en\u0026format=json\u0026countryCode=US"
    },
    {
        "id":  "toronto",
        "name":  "Toronto",
        "latitude":  43.70643,
        "longitude":  -79.39864,
        "timeZone":  "America/Toronto",
        "group":  "Americas",
        "geonameId":  6167865,
        "country":  "Canada",
        "source":  "https://geocoding-api.open-meteo.com/v1/search?name=Toronto\u0026count=10\u0026language=en\u0026format=json\u0026countryCode=CA"
    },
    {
        "id":  "vancouver",
        "name":  "Vancouver",
        "latitude":  49.24966,
        "longitude":  -123.11934,
        "timeZone":  "America/Vancouver",
        "group":  "Americas",
        "geonameId":  6173331,
        "country":  "Canada",
        "source":  "https://geocoding-api.open-meteo.com/v1/search?name=Vancouver\u0026count=10\u0026language=en\u0026format=json\u0026countryCode=CA"
    },
    {
        "id":  "sao-paulo",
        "name":  "Sao Paulo",
        "latitude":  -23.5475,
        "longitude":  -46.63611,
        "timeZone":  "America/Sao_Paulo",
        "group":  "Americas",
        "geonameId":  3448439,
        "country":  "Brazil",
        "source":  "https://geocoding-api.open-meteo.com/v1/search?name=Sao%20Paulo\u0026count=10\u0026language=en\u0026format=json\u0026countryCode=BR"
    }
]
