// Equatorial diameters and sidereal rotation from NASA NSSDCA. Orbit lengths
// use the NASA Science planet facts pages, rounded for this educational view.
// Rotation is deliberately distinguished from a sunrise-to-sunrise solar day.
export const PLANETS = [
  { id: 'mercury', name: 'Mercury', subtitle: 'Small world. Long days.', description: 'A rocky, cratered world that races around the Sun faster than any other planet.', story: 'Mercury is the smallest planet in our solar system. With almost no atmosphere to hold in heat, its surface swings between scorching sunlight and freezing darkness.', diameter: '4,879 km', rotation: '58.6 Earth days', year: '88 Earth days', type: 'Rocky planet', color: '#aaa49a', tilt: 0.034 },
  { id: 'venus', name: 'Venus', subtitle: 'Beyond the golden clouds.', description: 'Wrapped in thick clouds, this golden planetary neighbor keeps its surface hidden.', story: 'Venus is roughly Earth’s size, but its dense atmosphere traps extraordinary heat. It rotates slowly and in the opposite direction to most planets. The model shows its cloud tops, rather than the ground beneath them.', diameter: '12,104 km', rotation: '243 Earth days', year: '225 Earth days', type: 'Rocky planet', color: '#d7bb83', tilt: 177.4 },
  { id: 'earth', name: 'Earth', subtitle: 'A world to call home.', description: 'Blue oceans, shifting clouds, and the only world where we have found life.', story: 'Liquid water covers most of Earth’s surface. Its atmosphere and magnetic field help make this small rocky planet a place where life can thrive. The model’s surface and cloud maps are a fixed illustration, not live weather.', diameter: '12,756 km', rotation: '23.9 hours', year: '365 Earth days', type: 'Rocky planet', color: '#79a8cf', tilt: 23.4 },
  { id: 'mars', name: 'Mars', subtitle: 'The next horizon.', description: 'A rust-red desert with giant volcanoes, deep canyons, and traces of ancient water.', story: 'Mars is a cold, rocky world with a thin atmosphere. Its rusty color comes from iron minerals in the soil. Robotic explorers are studying its history and the environments that once existed there.', diameter: '6,792 km', rotation: '24.6 hours', year: '687 Earth days', type: 'Rocky planet', color: '#c8805e', tilt: 25.2 },
  { id: 'jupiter', name: 'Jupiter', subtitle: 'A giant in motion.', description: 'Vast cloud bands and swirling storms surround the largest planet in our solar system.', story: 'Jupiter is a gas giant made mostly of hydrogen and helium. Its Great Red Spot is an enormous, long-lived storm. Beneath the visible clouds, pressure rises into an interior very different from Earth’s.', diameter: '142,984 km', rotation: '9.9 hours', year: '11.9 Earth years', type: 'Gas giant', color: '#d2b49a', tilt: 3.1 },
  { id: 'saturn', name: 'Saturn', subtitle: 'A world of rings.', description: 'A gas giant surrounded by countless pieces of ice and rock, catching the sunlight.', story: 'Saturn’s rings are made of particles ranging from tiny grains to large chunks of ice and rock. The planet itself is mostly hydrogen and helium. Its pale cloud bands surround a world with no solid surface to stand on.', diameter: '120,536 km', rotation: '10.7 hours', year: '29.4 Earth years', type: 'Gas giant', color: '#dbc298', tilt: 26.7 },
  { id: 'uranus', name: 'Uranus', subtitle: 'A different kind of blue.', description: 'A pale blue-green ice giant that travels around the Sun tipped onto its side.', story: 'Uranus has an extreme axial tilt, giving it very unusual seasons. Methane in its atmosphere contributes to its blue-green color. Its faint, dark rings are omitted from this simplified showcase.', diameter: '51,118 km', rotation: '17.2 hours', year: '84 Earth years', type: 'Ice giant', color: '#a3d4d8', tilt: 97.8 },
  { id: 'neptune', name: 'Neptune', subtitle: 'At the edge of the familiar.', description: 'A distant ice giant with powerful winds, far beyond the warmth of Earth.', story: 'Neptune is the farthest of the eight planets from the Sun. Its atmosphere is dynamic, with fast winds and changing storms. This texture uses enhanced blue color to make its cloud features easier to see.', diameter: '49,528 km', rotation: '16.1 hours', year: '165 Earth years', type: 'Ice giant', color: '#6f92d9', tilt: 28.3 },
]

export const PLANET_FACTS_SOURCE = 'https://nssdc.gsfc.nasa.gov/planetary/factsheet/'
export const TEXTURE_SOURCE = 'https://www.solarsystemscope.com/textures/'
export const planetTexture = (id) => `/textures/planets/${id}.jpg`
export const findPlanet = (id) => PLANETS.find((planet) => planet.id === id) || PLANETS[5]
